### ISSUE TITLE
getStats() freezes Edge

### ISSUE THREAD

**Issue by fippo** [fippo/webrtc-externals#3]
the getStats calls somehow "freeze" Edge. Unclear whether it is the stats themselves or something in the drawing code. Currently deactivated by looking at the user agent

**Comment by fippo** [comment]
to re-activate revert 9b0d5d65bda0c89404ace47da2b7e626b8123b11

**Comment by fippo** [comment]
definetly in the drawing function, somewhere in drawSingleReport. Still works when returning before "Updates the graph". Problem seems to be in updateEnddate... probably the repaint function.

**Comment by fippo** [comment]
"not responding due to a long running script"... oh yes... :-/

**Comment by fippo** [comment]
https://github.com/fippo/webrtc-externals/blob/93ff1f02b09e3fab740ee255e9c82158c1925beb/webrtc-internals.js#L756-L768
is suspect... probably taking _very_ long for some reason.

**Comment by fippo** [comment]
deactivating the drawTimeLabels fixes the freeze issue. So its something about the data that makes that loop go crazy

**Comment by fippo** [comment]
doesn't seem to be related to the data. Just doing this 80 times a second seems too much for Edge...

**Comment by fippo** [comment]
looks like this is causing [issues in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1401389). Bad graph library... :-(

**Comment by LionelCapiez** [comment]
Hi,
Side-tracking a little bit (sorry), but which version of Edge was this? 
(I could not get the extension to work on either Edge 38 nor Edge 41  - except with a minor fix, see PR).
