### ISSUE TITLE
doesnt show stats on Edge inside build

### ISSUE THREAD

**Issue by arun3528** [fippo/webrtc-externals#5]
I am getting an error on this line. I think for some reason it thinks it is a chrome browser 
SCRIPT438: SCRIPT438: Object doesn't support property or method 'send'

  chrome.send('finishedDOMLoad');

**Comment by fippo** [comment]
see #3 for stats. The chrome.send is mostly harmless and caused by the decision to copy the chrome webrtc-internals code 1:1
