### ISSUE TITLE
No graphs shown in Edge

### ISSUE THREAD

**Issue by kekkokk** [fippo/webrtc-externals#7]
Hi @fippo !!
currently I'm trying to test your extension in Edge 40.15063.0.0.
The result is that I am able to see the gum requests tab and the peerconnection tab. 
The problem is that no graphs are shown. only the peerconnection log.
The last entry is the 'oniceconnectionstatechange' : connected.

This is also reproducible on another pc with the latest edge in the insider preview rc3.
Am I doing something wrong or is a known issue?

**Comment by fippo** [comment]
see #3 -- haven't had time to figure out what exactly causes this

**Comment by kekkokk** [comment]
I'm sorry, I saw the issue but I didn't understand you had completely disabled graphs in edge.
Thanks for your effort, btw, I really appreciate that!
Have a nice day!
